import Head from "next/head";
import type { NextPage } from "next";
import importSchedule from "~/utils/import-schedule";

const AdminPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex-1 overflow-auto p-4">
          <button onClick={() => void importSchedule()}>Import schedule</button>
        </div>
      </main>
    </>
  );
};

export default AdminPage;
