import { Button } from "flowbite-react";
import Head from "next/head";
import type { NextPage } from "next";
import Sidebar from "~/components/sidebar";
import importSchedule from "~/utils/import-schedule";

const AdminPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-50 dark:bg-gradient-to-br dark:from-gray-700 dark:to-gray-800 dark:text-gray-50">
        <Sidebar />
        <div className="flex-1 overflow-auto p-4">
          <Button onClick={() => void importSchedule()}>Import schedule</Button>
        </div>
      </main>
    </>
  );
};

export default AdminPage;
