import Head from "next/head";
import type { NextPage } from "next";
import importCars from "~/utils/import-cars";
import importSchedule from "~/utils/import-schedule";

const Button = ({ children, onClick }) => {
  return (
    <button
      className="inline-flex h-10 w-48 items-center justify-center rounded-md bg-slate-100 px-4 py-2 text-sm font-medium text-slate-900 transition-colors focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=open]:bg-slate-100 hover:bg-slate-200 active:scale-95 dark:bg-slate-700 dark:text-slate-100 dark:focus:ring-slate-400 dark:focus:ring-offset-slate-900 dark:data-[state=open]:bg-slate-800 dark:hover:bg-slate-800 dark:hover:text-slate-100"
      onClick={onClick}
    >
      {children}
    </button>
  );
};

const AdminPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <div className="flex flex-col gap-2 overflow-auto p-4">
          <Button onClick={() => void importSchedule()}>Import schedule</Button>
          <Button onClick={() => void importCars()}>Import cars</Button>
        </div>
      </main>
    </>
  );
};

export default AdminPage;
