import { type NextPage } from "next";
import Head from "next/head";
import ScheduleTable from "~/components/schedule-table";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>iRacing Schedule</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ScheduleTable />
      </main>
    </>
  );
};

export default Home;
