import { type NextPage } from "next";
import Head from "next/head";
import ScheduleTable from "~/components/schedule-table";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>iRacing Schedule</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="h-full">
        <ScheduleTable />
      </main>
    </>
  );
};

export default Home;
