import { type NextPage } from "next";
import Head from "next/head";

import Sidebar from "~/components/sidebar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-50 dark:bg-gradient-to-br dark:from-gray-700 dark:to-gray-800">
        <Sidebar />
        App
      </main>
    </>
  );
};

export default Home;
