import { type NextPage } from "next";
import Head from "next/head";

const Settings: NextPage = () => {
  return (
    <>
      <Head>
        <title>iRacing Schedule</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="h-full">Settings page</main>
    </>
  );
};

export default Settings;
